global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 127.0.0.1:9090

  - job_name: node
    static_configs:
      - targets:
          - 127.0.0.1:9100
        labels:
          host: ubuntu

  - job_name: ops-demo-http
    metrics_path: /probe

    params:
      module:
        - http_2xx

    static_configs:
      - targets:
          - http://127.0.0.1:8000/health
        labels:
          service: ops-demo

      - targets:
          - http://127.0.0.1:8001/health
        labels:
          service: ops-demo1

      - targets:
          - http://127.0.0.1:8002/health
        labels:
          service: ops-demo2

    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: 127.0.0.1:9115