PROMETHEUS_CONFIG_FILE="/etc/prometheus/prometheus.yml"
PROMETHEUS_BLACKBOX_CONFIG_FILE="/etc/prometheus/blackbox.yml"
PROMETHEUS_RULES_FILE="/etc/prometheus/rules/ops-demo.yml"

PROMETHEUS_PORT=9090
PROMETHEUS_NODE_PORT=9100
PROMETHEUS_BLACKBOX_PORT=9115
GRAPHITE_PORT=3000