PROMETHEUS_CONFIG_FILE="/etc/prometheus/prometheus.yml"
PROMETHEUS_BLACKBOX_CONFIG_FILE="/etc/prometheus/blackbox.yml"
PROMETHEUS_RULES_FILE="/etc/prometheus/rules/ops-demo.yml"
GRAFANA_PROMETHEUS_FILE="/etc/grafana/provisioning/datasources/prometheus.yml"
GRAFANA_DASHBOARD_JSON_FILE="/etc/grafana/dashboards/ops-demo/ops-demo-overview.json"
GRAFANA_DASHBOARD_OPS_DEMO_FILE="/etc/grafana/provisioning/dashboards/ops-demo.yml"

PROMETHEUS_PORT=9090
PROMETHEUS_NODE_PORT=9100
PROMETHEUS_BLACKBOX_PORT=9115
GRAFANA_PORT=3000
